version: '3.9'

networks:
  dh_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1

services:
  machine3:  # Machine3 must start first as it acts as the MITM relay
    image: python:3.9-alpine
    container_name: machine3
    networks:
      dh_network:
        ipv4_address: 10.0.0.4
    working_dir: /app
    volumes:
      - ./machine3:/app
    command: ["python", "main.py"]

  machine2:  # Machine2 should start after Machine3
    image: python:3.9-alpine
    container_name: machine2
    depends_on:
      - machine3
    networks:
      dh_network:
        ipv4_address: 10.0.0.3
    working_dir: /app
    volumes:
      - ./machine2:/app
    command: ["python", "main.py"]

  machine1:  # Machine1 should start last
    image: python:3.9-alpine
    container_name: machine1
    depends_on:
      - machine2
    networks:
      dh_network:
        ipv4_address: 10.0.0.2
    working_dir: /app
    volumes:
      - ./machine1:/app
    command: ["python", "main.py"]
